version: '3.7'
services:
  apache:
    image: evandrofernandes/webserver-template:1.0
    container_name: my-apache-app
    ports:
    - '80:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
